#!/usr/bin/env python3
# Stand-in for pw-play: get-volume-free; stores what it is fed, per target.
import os, sys
args = sys.argv[1:]
if args and args[0] in ("get-volume", "set-volume", "set-mute"):
    sys.exit(0)
target = args[args.index("--target") + 1] if "--target" in args else "default"
out = os.path.join(os.environ.get("FAKE_AUDIO_DIR", "/tmp"), "play-" + target)
with open(out, "ab") as f:
    while True:
        data = sys.stdin.buffer.read1(4096)
        if not data:
            break
        f.write(data)
        f.flush()
